name: Design Container WPE template initialization
description: This action handles repo initialization for the WPE template.
inputs:
    github_token:
        description: >
            Token to use GitHub API. It must have "repo" and "workflow" scopes so it can push to repo and edit workflows.
            It cannot be the default GitHub Actions token GITHUB_TOKEN. GitHub Action token's permissions are limited to the repository that contains your workflows.
            Provide token of the user that has rights to push to the repos that this action is suppose to update.
        required: true
    workflow_file:
        description: >
            The name of this workflow file (including extension)
        required: true
    theme_repo:
        description: >
            The repo for your starter theme
        required: true
    committer_username:
        description: >
            The username (not display name) of the committer that will be used in the commit of changes in the workflow file in specific repository.
            In the format `web-flow`.
        default: web-flow
        required: false
    committer_email:
        description: >
            The email of the committer that will be used in the commit of changes in the workflow file in specific repository.
            In the format `noreply@github.com`.
        default: noreply@github.com
        required: false
    commit_message:
        description: >
            It is used as a commit message when pushing changes with global workflows. 
            It is also used as a title of the pull request that is created by this action.
        default: Initialize new template
        required: false
runs:
    using: node12
    main: dist/index.js
branding:
    icon: git-merge
    color: blue
